### ISSUE TITLE
supprimer les attributs langue vides

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/mimo#1]

**Comment by marie-ototoi** [comment]
je trouve ça bizarre d'avoir ces labels préférés qui n'ont pas de langue (que ce soit ="" ou sans attribut)
dans l'optique d'une utilisation des données par un programme, n'est-il pas plus pratique et plus clair de nommer cette langue (pivot ou default par exemple)
il faut sans doute rajouter aussi une note qui explique le choix de cette langue pivot

**Comment by rbailly** [comment]
voui mais les langues font références à un code bien précis ( fr, en, etc. ) Je ne suis pas sûr de savoir comment procéder pour expliquer la démarche si ce n'est ajouter une note dans le conceptScheme ?

**Comment by marie-ototoi** [comment]
oui la note dans le concept scheme c'est sur

mais après pour que ce soit utilisable il faut un code, j'imagine qu'aucun dev ne sera très content de faire une requete sur "tous les label préférés qui n'ont pas de code langue",
et je ne connais pas encore SPARQL mais j'imagine que ça peut même forcer à faire une requête biscornue

si on considère que c'est une façon intéressante de procéder pour d'autres data où le mot "pivot" peut venir de différentes langues, peut-être qu'on peut soumettre ça aux gens qui font les codes pays ? même si c'est long et qu'en attendant on a un code non standard, ça permettrait d'avoir des données vraiment standard à un moment
et il y a bien un code pour l'interlingua et l'esperanto

ou bien on n'exporte pas la version pivot qui rend les données non standard ? elle semble peu susceptible d'être affichée si ce concept de langue pivot n'est pas diffusé et expliqué ?

**Comment by rbailly** [comment]
Je ne crois pas trop en la création d'une langue par les gens qui gèrent les codes de langue. .  .
Par contre tu as raison pour être vraiment standard, il vaut probablement mieux ne pas exporter la langue pivot, sinon on risque de ne pas être compris et donc pas utilisé . +1
