### ISSUE TITLE
URI Hornbostel & Sachs

### ISSUE THREAD

**Issue by marie-ototoi** [philharmoniedeparis/mimo#14]
Est-ce qu'on utilise des PURL ?

**Comment by marie-ototoi** [comment]
J'ai créé un compte, et récupéré le format du fichier xml pour importer un lot d'urls
Je vais faire un script pour générer ce xml à partir de notre xml h&s

**Comment by rbailly** [comment]
UN compte sur PURL ?

**Comment by marie-ototoi** [comment]
En vérifiant mon traitement des friendly name en vue des URI je tombe sur un label bizarre : 
"314.11-4-8+421.132-62-8 True board zithers without resonator, sounded by hammers or beaters, with keyboard + Sets of free reeds, with flexible air reservoir, with keyboard"
c'est l'id 6480

en fait ce sont 2 concepts publiés comme 1, du coup ça me semble ennuyeux

idem pour le 6481, 6225, 6488, 6418, 6410, 6411, 6229, 6230, 6412, 6413, 6231, 6492, 6233, 6414, 6232, 6415, 6234, 6493, 6235, 6416, 6236, 6417, 6494, 6495,

**Comment by marie-ototoi** [comment]
J'aurais besoin d'avancer sur ce point qui me semble bloquant, on en parle quand tu peux !

**Comment by marie-ototoi** [comment]
Sur la question des licenses, à lire éventuellement le D3.5
http://datalift.org/?page_id=26

**Comment by rbailly** [comment]
Tu en as une version imprimée ?
