### ISSUE TITLE
Gérer les synonymes

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/mimo#2]
pour l'instant les synonymes de termes n'apparaissent pas comme tels dans le SKOS
voir pour exemple : "Abele", synonyme de "Agbomboya"

**Comment by marie-ototoi** [comment]
alors ça soulève encore des questions...

ils disent ici http://www.w3.org/TR/skos-primer/#seccorrespondencesISO
que la différence entre SKOS et un thesaurus classique c'est que SKOS fonctionne par Concepts / vs un thesaurus par termes

j'ai un export xml qui correspond à un thesaurus classique avec tous les termes à plat

et donc il faudrait que tous les synonymes non préférés n'apparaissent plus comme concepts mais uniquement comme termes alternatifs du concept préféré

-> est ce que les relations de type UF dans la base de données sont bien des synonymes au sens d'un même concept ? ça vaut dire que si j'ai plusieurs termes alternatifs dans chaque langue je ne serai plus capable de les faire correspondre - ce qui est logique si on a une URI par concept : si je cherche un terme je tombe toujours sur l'URI du terme préféré, pas celle du terme que j'ai cherché - si je change de langue je tombe sur la traduction du terme préféré, pas celle du terme que je cherchais

-> il faut que je vérifie si j'arrive à gérer ça en xsl

**Comment by marie-ototoi** [comment]
je confirme qu'il faudrait que j'enlève ces termes au niveau du traitement du xml en python
en xsl je ne suis pas capable d'aller voir en dehors de la boucle dans laquelle je suis si le terme est un synonyme ailleurs et si donc je ne dois pas l'afficher
