### ISSUE TITLE
ajouter des références à dbpedia

### ISSUE THREAD

**Issue by marie-ototoi** [philharmoniedeparis/mimo#3]
Là ça se gâte parce que les données ne sont pour l'instant pas dans la base et c'est un gros morceau de les y ajouter mais dans l'Excel que je te met en copie. Peut-on récupére les infos (URIs DBPedia )de cet Excel et les ajouter dans le SKOS en attendant que ces informations soient saisies par Valérie ?

**Comment by marie-ototoi** [comment]
ça je le fais au niveau du python pour avoir un xml propre qui peut servira de base dans la demande à Archimed ?

**Comment by rbailly** [comment]
Bien vu. . .

**Comment by marie-ototoi** [comment]
je n'arrive pas à retrouver automatiquement le lien vers dbpedia à partir du lien wikipedia
pourtant tu m'avais montré...

**Comment by rbailly** [comment]
http://wiki.dbpedia.org/Datasets2014 (chapitre 3)

**Comment by marie-ototoi** [comment]
http://en.wikipedia.org/wiki/Bow_(music)

http://xx.dbpedia.org/resource/Name
je comprends pas où je trouve resource

-> ça ne marche pas http://en.dbpedia.org/wiki/Bow_(Music)
-> ça non plus http://en.dbpedia.org/Bow_(Music)

**Comment by rbailly** [comment]
Tu as raison il semble qu'il y ait un soucis . En théorie 
http://dbpedia.org/resource/Bow_(Music)
devrait fonctionner. ça répond bien quelque chose mais c'est pas très intéressant. Je ne comprends pas bien non plus, on dirait que quelque chose est cassé. . .

**Comment by marie-ototoi** [comment]
ok
pas pour celui-là mais pour la plupart ça a l'air de marcher avec page au lieu de resource, et sans la langue
http://dbpedia.org/page/Mellotron
on convertit comme ça et on enlèvera les cassés ?

**Comment by rbailly** [comment]
Ok. Mais attention cependant de bien utiliser

http://dbpedia.org/resource/Mellotron

et non pas

http://dbpedia.org/page/Mellotron

En effet, page est la "page" HTML pour les humains, vers laquelle on est redirigé après un 303 parceque le serveur comprend que le client est un browser. Les programmes préfèreront la version "pure RDF" derrière resource.
